# Generated by Django 4.2.20 on 2025-04-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embedded_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.CharField(max_length=20)),
                ("end_time", models.CharField(blank=True, max_length=20, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
    ]
