# Generated by Django 4.2.20 on 2025-04-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embedded_app", "0002_alert"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AccX", models.FloatField()),
                ("AccY", models.FloatField()),
                ("AccZ", models.FloatField()),
                ("GyroX", models.FloatField()),
                ("GyroY", models.FloatField()),
                ("GyroZ", models.FloatField()),
                ("temperature", models.FloatField()),
                ("vibration_detected", models.BooleanField(default=False)),
                ("timestamp", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
