# Generated by Django 4.2.20 on 2025-05-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embedded_app", "0004_sensordata_latitude_sensordata_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
    ]
