# Generated by Django 4.2.20 on 2025-05-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embedded_app", "0005_alter_sensordata_latitude_alter_sensordata_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="location",
            field=models.CharField(default="-", max_length=100),
            preserve_default=False,
        ),
    ]
