# Generated by Django 4.2.20 on 2025-05-01 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("embedded_app", "0006_alert_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.FloatField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "end_route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_end",
                        to="embedded_app.route",
                    ),
                ),
                (
                    "start_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_start",
                        to="embedded_app.route",
                    ),
                ),
            ],
        ),
    ]
