# Generated by Django 4.2.20 on 2025-05-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embedded_app", "0008_devicetoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
