# Generated by Django 4.2.20 on 2025-05-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embedded_app", "0009_route_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="location",
            field=models.CharField(blank=True, default="-", max_length=100),
            preserve_default=False,
        ),
    ]
